### 상품 목록 조회
GET http://localhost:8080/api/products
X-API-Key: demo-key-client-01

### 권한 거부 예제
GET http://localhost:8080/api/reports/sales
X-API-Key: demo-key-client-10

### API key 누락 예제
GET http://localhost:8080/api/products

### 시간대별 호출 수
GET http://localhost:8080/api/stats/calls?bucket=1%20minute&from=2026-07-07T00:00:00Z&to=2026-07-07T01:00:00Z

### endpoint Top N
GET http://localhost:8080/api/stats/top-endpoints?from=2026-07-07T00:00:00Z&to=2026-07-07T01:00:00Z&limit=10
