###
POST http://localhost:8080/stream/add
Content-Type: application/json

{
  "baseRequest": {
    "key": "orders"
  },
  "fields": {
    "product": "laptop",
    "quantity": "1",
    "price": "1500000"
  }
}

###
POST http://localhost:8080/stream/add
Content-Type: application/json

{
  "baseRequest": {
    "key": "orders"
  },
  "fields": {
    "product": "mouse",
    "quantity": "2",
    "price": "800000"
  }
}

###
GET http://localhost:8080/stream/length?key=orders
Content-Type: application/json

###
GET http://localhost:8080/stream/read?key=orders&offset=0-0&count=10
Content-Type: application/json

###
POST http://localhost:8080/stream/group
Content-Type: application/json

{
  "baseRequest": {
    "key": "orders"
  },
  "group": "order-processors",
  "offset": "0-0"
}

###
GET http://localhost:8080/stream/group/read?key=orders&group=order-processors&consumer=consumer-1&count=2
Content-Type: application/json

###
POST http://localhost:8080/stream/group/ack
Content-Type: application/json

{
  "baseRequest": {
    "key": "orders"
  },
  "group": "order-processors",
  "recordId": "0-0"
}
