spring:
  config:
    activate:
      on-profile: docker
  data:
    redis:
      host: redis
      port: 6379
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
        provider:
          keycloak:
            authorization-uri: http://localhost:9000/realms/oidc-multi-app-example/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/realms/oidc-multi-app-example/protocol/openid-connect/token
            user-info-uri: http://keycloak:8080/realms/oidc-multi-app-example/protocol/openid-connect/userinfo
            jwk-set-uri: http://keycloak:8080/realms/oidc-multi-app-example/protocol/openid-connect/certs
            user-name-attribute: preferred_username

app:
  security:
    end-session-uri: http://localhost:9000/realms/oidc-multi-app-example/protocol/openid-connect/logout
