[versions]
dependencyManagement = "1.1.7"
kotlin = "2.4.10"
springBoot = "3.5.16"

[libraries]
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis" }
spring-boot-starter-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }
spring-session-data-redis = { module = "org.springframework.session:spring-session-data-redis" }

[plugins]
dependency-management = { id = "io.spring.dependency-management", version.ref = "dependencyManagement" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
