apiVersion: 1

datasources:
  - uid: prometheus
    name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - uid: timescaledb-api-stats
    name: TimescaleDB API Stats
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: api_stats
    user: api_stats
    secureJsonData:
      password: api_stats
    jsonData:
      sslmode: disable
      postgresVersion: 1700
      timescaledb: true
    editable: true
