services:
  mysql:
    image: 'mysql:8.4.3'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=mypassword'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=myuser'
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    ports:
      - '3306:3306'